### ISSUE TITLE
Doubts about the variable init.k.mat 

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/FeralCatEradication#21]
We believe that [line 610:](https://github.com/KathrynVenning/FeralCatEradication/blob/bc1da3226d9eff6487af134bf4a6f76a4ac5e190/FeralCatEradication.R#L610)

```
init.k.mat[,i+1] <- n.mat[,i+1]
```
should be:
```
init.k.mat[,i+1] <- k.mat[,i+1]
```

---

As the variable `init.k.mat`  is used to calculate the number of killed cats per year using baiting and trapping the first two years, so the variable `init.k.mat` should not have the information of remnant cats. 

We think that the variable `init.k.mat` represents to despatched cats the two first years. And the variable `n.mat[,i+1] <- n.mat[,i+1] - k.mat[,i+1]` in [line 609](https://github.com/KathrynVenning/FeralCatEradication/blob/bc1da3226d9eff6487af134bf4a6f76a4ac5e190/FeralCatEradication.R#L609) represents remnant cats.

**Comment by devarops** [comment]
https://github.com/KathrynVenning/FeralCatEradication/issues/5
