### ISSUE TITLE
Mean parameter values and their standard deviation (SD) used in the stochastic model (m.vec)

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/FeralCatEradication#25]
We belive that [line 167](https://github.com/KathrynVenning/FeralCatEradication/blob/bc1da3226d9eff6487af134bf4a6f76a4ac5e190/FeralCatEradication.R#L167):

```
fert.stch <- rnorm(length(popmat[,1]), popmat[1,], m.sd.vec)
```
Should be:
```
fert.stch <- rnorm(length(popmat[,1]), m.vec, m.sd.vec)
```
Since `popmat[,1]` is modified in line [line 173](https://github.com/KathrynVenning/FeralCatEradication/blob/bc1da3226d9eff6487af134bf4a6f76a4ac5e190/FeralCatEradication.R#L173) inside the for-loop ([line 160](https://github.com/KathrynVenning/FeralCatEradication/blob/bc1da3226d9eff6487af134bf4a6f76a4ac5e190/FeralCatEradication.R#L160)):

```
popmat[1,] <- fert.stoch
```

However, `m.vec` stays constant.

This because, when rewriting the first row of the Leslie matrix (`popmat [1,]`) with new stochastic fertility data in each iteration, the parameters of the normal distribution change. The mix up is due to the fact that `popmat [1,]` will no longer be constant and therefore we can no longer assume that it contains the mean of the fertility distribution. This issue is causing the credibility interval to be wider.

In its current state, it looks this way:

![image](https://user-images.githubusercontent.com/35377740/141001850-d2204339-bbc9-4095-b8e9-af756d667771.png)

But it should look like this:

![image](https://user-images.githubusercontent.com/9456708/141001788-75f2e8f7-fcba-475a-906f-24e58fe0dbd2.png)

**Comment by nepito** [comment]
> We assumed a Gaussian distribution around the mean of fertility and the β distribution for survival probability, using the standard deviations for resampling of each (Table 1).

`Lineas 29-31` en el archivo `FeralCatEradication.R`
```
## create vectors 
#fertility 
m.vec <- c((0.745/3), 0.745, 2.52, 2.52, 2.52, 2.52, 1.98) ## KI cat birth rates matrix, data for female offsping produced each year. Data from Budke, C & Slater, M (2009)
```

`Lineas 47-52` en el archivo `FeralCatEradication.R`
```
# create matrix
popmat <- matrix(data = 0, nrow=age.max, ncol=age.max)
diag(popmat[2:age.max,]) <- s.vec
popmat[age.max,age.max] <- 0
popmat[1,] <- m.vec
popmat.orig <- popmat ## save original matrix
```
`Lineas 160-179` en el archivo `FeralCatEradication.R`
```
for (i in 1:t) {
    # stochastic survival values
    s.alpha <- estBetaParams(s.vec, s.sd.vec^2)$alpha
    s.beta <- estBetaParams(s.vec, s.sd.vec^2)$beta
    s.stoch <- rbeta(length(s.alpha), s.alpha, s.beta)
    
    # stochastic fertilty sampler (gaussian)
    fert.stch <- rnorm(length(popmat[,1]), popmat[1,], m.sd.vec)
    fert.stoch <- ifelse(fert.stch < 0, 0, fert.stch)
    
    totN.i <- sum(n.mat[,i])
    pred.red <- a.lp/(1+(totN.i/b.lp)^c.lp)
    
    popmat[1,] <- fert.stoch
    diag(popmat[2:age.max,]) <- s.stoch*pred.red
    #popmat[age.max,age.max] <- 0
    
    n.mat[,i+1] <- popmat %*% n.mat[,i]
    
  } # end i loop
```

**Comment by devarops** [comment]
https://github.com/KathrynVenning/FeralCatEradication/issues/4
